name: Send Website Link via Email

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  send_email:
    runs-on: ubuntu-latest
    steps:
      - name: Send Email
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.GMAIL_USERNAME }}
          password: ${{ secrets.GMAIL_PASSWORD }}
          subject: "Website Preview"
          from: saadiqbalbutt89@gmail.com
          to: saad89.linux@gmail.com
          body: |
            <html>
            <body>
              <p>Preview of Your Website:</p>
              <p>Click the link below to view your website:</p>
              <a href="https://your-website-url.com">Visit Your Website</a>
            </body>
            </html>
          contentType: text/html
