name: Send Email with Website Content

on:
  push:
    branches:
      - my-first-branch
  workflow_dispatch:
    inputs:
      recipient_email:
        description: 'Recipient Email Address'
        required: true
      subject:
        description: 'Email Subject'
        required: true
      body:
        description: 'Email Body'
        required: true

jobs:
  send_email:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x  # Choose a Python version

      - name: Run Python Script
        run: python scripts/send_email.py  # Adjust the path to your script
        env:
          GMAIL_APP_PASSWORD: ${{ secrets.GMAIL_PASSWORD }}
          RECIPIENT_EMAIL: ${{ github.event.inputs.recipient_email }}
          SUBJECT: ${{ github.event.inputs.subject }}
          BODY: ${{ github.event.inputs.body }}
