name: Send Email with Website Content

on:
  push:
    branches:
      - main  # Change to your repository's main branch name

jobs:
  send_email:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x  # Choose a Python version

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install smtplib

      - name: Run Python Script
        run: python path/to/your/script/send_email.py  # Replace with the actual path to your Python script
        env:
          GMAIL_APP_PASSWORD: ${{ secrets.GMAIL_PASSWORD }}

