name: Send Website HTML via Email

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  send_email:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Generate HTML
        working-directory: .
        run: echo "<!DOCTYPE html><html><head><title>Your Website</title></head><body><h1>Hello World!</h1></body></html>" > generated_html.html

      - name: Send Email
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.GMAIL_USERNAME }}
          password: ${{ secrets.GMAIL_PASSWORD }}
          subject: "Static Website HTML"
          from: your_email@example.com
          to: saad89.linux@gmail.com
          body: |
            Here's the HTML code of the static website:

            $(cat generated_html.html)
