name: Send Email

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Add this trigger to enable manual execution

jobs:
  send-email:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Send Email
        run: |
          python scripts/send_email.py
