name: Send Email

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  send_email:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Read HTML File
        id: read-html
        run: |
          html_content=$(cat index.html)
          echo "::set-output name=content::$html_content"

      - name: Send Email
        run: |
          echo "Subject: Static Website HTML
          From: saadiqbalbutt89@gmail.com
          To: saad89.linux@gmail.com
          Content-Type: text/html

          <!DOCTYPE html>
          <html>
          <body>
            <p>Here's the HTML code of the static website:</p>
            <pre>
              ${{ steps.read-html.outputs.content }}
            </pre>
          </body>
          </html>
          " | sendmail -t
