name: Send Website Content via Email

on:
  push:
    branches:
      - my-first-branch  # Replace with your branch name
  workflow_dispatch:  # Add manual trigger option

jobs:
  send_email:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set Up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install Dependencies
        run: npm install

      - name: Read Index HTML
        id: read-html
        run: |
          HTML_CONTENT=$(cat index.html)
          echo "::set-output name=content::$HTML_CONTENT"

      - name: Send Email
        uses: dawidd6/action-send-mail@v2
        with:
          server_address: smtp.gmail.com  # Google SMTP server address
          server_port: 587  # Google SMTP server port
          username: ${{ secrets.GMAIL_USERNAME }}  # Store your Gmail username as a secret
          password: ${{ secrets.GMAIL_PASSWORD }}  # Store your Gmail password as a secret
          subject: "Check Out Our Website!"
          body: ${{ steps.read-html.outputs.content }}  # Use the content directly
          to: saad89.linux@gmail.com  # Replace with the recipient's email address
          from: saadiqbalbutt89@gmail.com  # Replace with the sender's email address
          content_type: text/html  # Use HTML content type
